json.item product.id
json.controller product.name
json.price product.price
json.description product.description
json.image product.images
json.supplier product.supplier
json.discount product.is_discounted?
json.tax product.tax
json.category product.categories
json.user current_user