json.item product.id
json.controller product.name
json.price product.price
json.description product.description
json.image product.image
json.supplier product.supplier
json.discount product.is_discounted?
json.tax product.tax
json.total product.total
